"""Initial migration

Revision ID: f6cb4adc5b93
Revises: 
Create Date: 2026-06-25 20:40:54.134666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6cb4adc5b93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_asset_type_value')
    )
    op.create_index(op.f('ix_asset_type'), 'asset', ['type'], unique=False)
    op.create_index(op.f('ix_asset_value'), 'asset', ['value'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('asset_tag',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('target_asset_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_relationship_type'), 'relationship', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationship_source_asset_id'), 'relationship', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_relationship_target_asset_id'), 'relationship', ['target_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_target_asset_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_source_asset_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_relationship_type'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_table('asset_tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_asset_value'), table_name='asset')
    op.drop_index(op.f('ix_asset_type'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
